version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 6
      min-occurrences: 8
    gocyclo:
      min-complexity: 20
    lll:
      line-length: 240
    nakedret:
      max-func-lines: 0
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        text: G104
      - linters:
          - gosec
        path: _test\.go
        text: G601
      - linters:
          - gosec
        path: _test\.go
        text: G107
      - linters:
          - staticcheck
        path: _test\.go
        text: SA5011
      - linters:
          - staticcheck
        text: SA5001
      - linters:
          - staticcheck
        text: ST1003
      - linters:
          - staticcheck
        text: should have( a package)? comment
      - linters:
          - gosec
        text: G404
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
