
FROM --platform=$BUILDPLATFORM golang:1.26@sha256:595c7847cff97c9a9e76f015083c481d26078f961c9c8dca3923132f51fe12f1 AS builder

ENV GO11MODULE=on

# These ARGs to be populated by Docker Buildx call
ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

COPY ["go.mod", "go.sum", "./"]

RUN ["go", "mod", "download"]

COPY . .

RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -v -o unused-exporter ./cmd/unused-exporter


FROM alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

COPY --from=builder /app/unused-exporter /app/

EXPOSE 8080

ENTRYPOINT ["/app/unused-exporter"]
