FROM --platform=$BUILDPLATFORM golang:1.26@sha256:45a5f7a810238aabcbad211d70b9ae082022d96f7c7259e94041ad1b933575ac AS builder

ENV GO11MODULE=on

# These ARGs to be populated by Docker Buildx call
ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

COPY ["go.mod", "go.sum", "./"]

RUN ["go", "mod", "download"]

COPY . .

RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -v -o unused-exporter ./cmd/unused-exporter


FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

COPY --from=builder /app/unused-exporter /app/

EXPOSE 8080

ENTRYPOINT ["/app/unused-exporter"]
