FROM --platform=$BUILDPLATFORM golang:1.27@sha256:f44f6e88636cfb311f9ebace870ded69d943f227bb3cb27d32ffd84ea18c43ea AS builder

ENV GO11MODULE=on

# These ARGs to be populated by Docker Buildx call
ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

COPY ["go.mod", "go.sum", "./"]

RUN ["go", "mod", "download"]

COPY . .

RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -v -o unused-exporter ./cmd/unused-exporter


FROM alpine:3.23@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40

COPY --from=builder /app/unused-exporter /app/

EXPOSE 8080

ENTRYPOINT ["/app/unused-exporter"]
